## NoteBook 4

## **In This NoteBook We Will Learn Numpy**

## **Why NumPy?**

NumPy powers Pandas under the hood
A library that adds support for multi-dimensional arrays (like matrices)
Great for calculations, transformations, and memory-efficient data structures
Enables fast mathematical operations on large datasets.
Replaces slow Python loops with optimized, C-backed code, he your computations are much faster.

**> Speed & Efficiency**
Faster computations with optimized C-backed arrays.
**> Powerful Multidimensional Arrays**
Efficient handling of large datasets and matrices.
**> Rich Mathematical Functions**
Supports linear algebra, Fourier transforms, and statistics.
**> Broadcasting & Vectorization**
Write cleaner and faster code, no need for loops!

## **Import Numpy**

In [4]:
import numpy as  np 

## Creating Array

In [5]:
# Creating 1D Array 

Array1 = np.array([1,2,3,4,5])


# To Return the Dimension of The Array Use .ndim
print(Array1)
Array1.ndim
print("The Type Of Array Is : ",type(Array1))
print("The Data Type Of Array Is : ",  Array1.dtype)

[1 2 3 4 5]
The Type Of Array Is :  <class 'numpy.ndarray'>
The Data Type Of Array Is :  int64


In [6]:
# Creating 2D Array 

Array2 = np.array([[1.0,2.0,3.0,4.0],[5.0,6.0,7.0,8.0]])
print(Array2)
print("The Dimension Of The Array Is : ",Array2.ndim)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
The Dimension Of The Array Is :  2


In [7]:
# To Print The Type Of The Array Use Type()

print("The Type Of Array Is : " , type(Array2))

The Type Of Array Is :  <class 'numpy.ndarray'>


In [8]:
# To Print The Data Type Of The Array Use .dtype()

print("The Data Type Of Array Is : ", Array2.dtype)

The Data Type Of Array Is :  float64


In [9]:
# To Print The Shape Of The Array Use .shape

print("The Shape Of The Array IS : " , Array2.shape)

The Shape Of The Array IS :  (2, 4)


## Array Indexing And Slicing

In [10]:
Array3 = np.array([[1,2,3,0],[4,5,6,0],[7,8,9,0]])
print(Array3)

[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]


In [11]:
# Where Is The Element Location Row 1 And Column 2 ?

print(Array3[1,2])

6


In [12]:
# Print The Second Row In This Array With All Element

print("The Second Row Is : " , Array3[1,:])

The Second Row Is :  [4 5 6 0]


In [13]:
# Print The Second To Last Row

print("The Second To Last Row Is : ",Array3[-2,:])

The Second To Last Row Is :  [4 5 6 0]


In [14]:
# Print The Last Coloum 

print("The Last Column Is : " , Array3[:,-1])

The Last Column Is :  [0 0 0]


In [15]:
# Print The Second Column

print("The Second Column Is : ",Array3[:,1])

The Second Column Is :  [2 5 8]


In [16]:
print(Array3)

[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]


In [17]:
# Print The Middle 2 Element In The Row

print("The Middle Two Element In The Array Is : ", Array3[1,1:3])

The Middle Two Element In The Array Is :  [5 6]


In [18]:
# To Update A new Value In The Array Use 

Array3[1,1]=0

print("The Array After Set A new Value Into The Array : \n" , Array3)

The Array After Set A new Value Into The Array : 
 [[1 2 3 0]
 [4 0 6 0]
 [7 8 9 0]]






## Create Ones Zeros and Identity matrix





In [19]:
# Create Zeros Matrex 

Zeros_Matrix = np.zeros((2,3))
print(Zeros_Matrix)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
# Create Ones Matrix 

Ones_Matrix = np.ones((2,3))
print(Ones_Matrix)

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
# Create Array Full With Specific Number

Full_Matrix = np.full((2,3),4)
print(Full_Matrix)

[[4 4 4]
 [4 4 4]]


In [22]:
# Create Array Full With Specific String

Full_Matrix = np.full((2,3),"Data")
print(Full_Matrix)

[['Data' 'Data' 'Data']
 ['Data' 'Data' 'Data']]


In [23]:
# Create The Identity Matrix "That Filled With Ones At The Diagonal "

Identety_Matrix = np.identity(3)
print(Identety_Matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# Chek The Data Type Of The Array

print(Identety_Matrix.dtype)

float64


**Create Array With Random Numbers**

In [25]:
# The Random.rand() Create A Random Numbers Btween 0 And 1

Random_Numbers = np.random.rand(2,3)
print(Random_Numbers)

[[0.10303692 0.71873061 0.98746785]
 [0.84908914 0.38678483 0.0997161 ]]


In [26]:
# np.random.randint creates array of random numbers between specified start and end integer numbers of specific size

e=np.random.randint(1,6,size=(2,3)) #end is not included
print(e)

[[4 3 4]
 [4 1 1]]


**Sync Arrays**


In [27]:
# 2 Arrays that affect one another

x1=np.array([[1,2,3], [4,5,6]]) 
print(x1,"\n")

#Any change in x2 will be applied on x1
x2 = x1
x2[0,1]=10
print("x1","\n",x1,"\n\n", "x2","\n",x2)

[[1 2 3]
 [4 5 6]] 

x1 
 [[ 1 10  3]
 [ 4  5  6]] 

 x2 
 [[ 1 10  3]
 [ 4  5  6]]


In [28]:
# 2 Arrays that do not affect one another

y1=np.array([[1,2,3], [4,5,6]])
print(y1,"\n")

#copy() creates copy of y1 so any change in y2 will not be applied on y1

y2 = y1.copy()
print("y1", "\n",y1,"\n\n", "y2","\n",y2)


[[1 2 3]
 [4 5 6]] 

y1 
 [[1 2 3]
 [4 5 6]] 

 y2 
 [[1 2 3]
 [4 5 6]]


In [29]:
# 2 Arrays that do not affect one another

y1=np.array([[1,2,3], [4,5,6]])
print(y1,"\n")

#copy() creates copy of y1 so any change in y2 will not be applied on y1

y2 = y1.copy()
y2[0,1]=10
print("y1", "\n",y1,"\n\n", "y2","\n",y2)

[[1 2 3]
 [4 5 6]] 

y1 
 [[1 2 3]
 [4 5 6]] 

 y2 
 [[ 1 10  3]
 [ 4  5  6]]


## Arithmatic Operations


In [30]:

# Arithmatic Operations on Arrays

arr=np.array([[1,2,3,4], [5,6,7,8]])

print("arr", "\n",arr,"\n")
print("arr+2","\n",arr+2,"\n")
print("arr-2", "\n",arr-2,"\n")
print("arr*2","\n",arr*2,"\n")
print("arr/2", "\n",arr/2,"\n")
print("arr**2","\n",arr**2,"\n")

arr 
 [[1 2 3 4]
 [5 6 7 8]] 

arr+2 
 [[ 3  4  5  6]
 [ 7  8  9 10]] 

arr-2 
 [[-1  0  1  2]
 [ 3  4  5  6]] 

arr*2 
 [[ 2  4  6  8]
 [10 12 14 16]] 

arr/2 
 [[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]] 

arr**2 
 [[ 1  4  9 16]
 [25 36 49 64]] 



## Useful NumPy Functions for Data Work

In [ ]:
# Extend An Array With A Repeat

Array4 = np.array([[1,2,3],[4,5,6]])

# Repeate (Array , Number) Flattening The Array And Repeate The Array Number Of Times

Array01 = np.repeat(Array4 , 2)
print("Araay01 : ", "\n" , Array01 , "\n")

Araay04 :  
 [1 1 2 2 3 3 4 4 5 5 6 6] 



In [40]:
# If the axis is specified no flattening will happen

Array02 = np.repeat(Array4 , 2 , axis= 0)  # 0 == Rows
print("Array02 : ", "\n",Array02,"\n")



Array02 :  
 [[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]] 



In [41]:
Array03 = np.repeat(Array4 , 2 , axis= 1)  # 1 == Columns
print("Array03 : ", "\n",Array03,"\n")

Array03 :  
 [[1 1 2 2 3 3]
 [4 4 5 5 6 6]] 



In [42]:
# Create a bigger Array using smaller ones through stacking

a=np.array([1,2,3,4])
print("a", a)

b=np.array([5,6,7,8])
print("b", b)


a [1 2 3 4]
b [5 6 7 8]


In [ ]:
#np.vstack creates vertical stack of specific order ([order])

print("vertical", "\n", np.vstack([a,b,a,b]), "\n")


vertical 
 [[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]] 



In [45]:
#np.hstack creates horizontal stack of specific order ([order])

print("horizontal", np.hstack([b,a,b,a]))

horizontal [5 6 7 8 1 2 3 4 5 6 7 8 1 2 3 4]


## Concatenate Arrays


In [49]:
# Create Bigger Array through concatenating smaller ones

k=np.array([[1,2,3,4],[5,6,7,8]])
print(k,'\n')

k1=np.array([[9,10,11,12], [13,14,15,16]])
print(k1, '\n')

print("Concatenate")

print(np.concatenate ((k,k1), axis=0), "\n") #0=row (on top) ~ Vtaking

print(np.concatenate ((k,k1), axis=1), "\n") #1 = column (Beside) ~Hstaking



[[1 2 3 4]
 [5 6 7 8]] 

[[ 9 10 11 12]
 [13 14 15 16]] 

Concatenate
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]] 



In [50]:
# Comparing With Stacking

print("Stacking")

print(np.vstack([k,k1]) , "\n" )

print(np.hstack([k,k1]))

Stacking
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


## Array Manipulation (Generate, Reshape and Transpose Arrays)


In [ ]:
#np.arange(start, end, number of steps) creates array end is not included

x = np.arange(1,10,2)
print(x)

[1 3 5 7 9] 



In [54]:
#np.linspace(start, end, number of samples) creates evenly spaced samples

y = np.linspace(1,100,10)
print(y)


[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [59]:
arr=np.array([[1,2,3,4,5,6,7], [8,9,10, 11, 12, 13, 14]])
print("arr", "\n",arr)

#arr.reshape (Rows, columns) changes the array size (before 7*2=14, after must equal 14)

print("\n Array After Reshaping : \n" , arr.reshape(7,2))

arr 
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

 Array After Reshaping : 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]


In [60]:
#np.transpose(arr1)-> row-column and column=row

print("Array After Transpoing : \n",np.transpose(arr))

Array After Transpoing : 
 [[ 1  8]
 [ 2  9]
 [ 3 10]
 [ 4 11]
 [ 5 12]
 [ 6 13]
 [ 7 14]]


In [61]:
# Flatining The Array 
print("Flattend Array : \n ", arr.flat[:])

Flattend Array : 
  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## 
Append Array to Another

In [62]:
# Append an Array to another array

u=np.array([[1,2,3,4], [5,6,7,8]])
print("u","\n",u,"\n")
print("-----------------------------------------")
u1=np.append(u, [[9,10,11,12]], axis=0) #Underneath
print("u1","\n",u1,"\n")
print("-----------------------------------------")
u2=np.append(u, [[5], [9]], axis=1) # print("u2", "\n", u2,"\n")
print("u2","\n",u2)

u 
 [[1 2 3 4]
 [5 6 7 8]] 

-----------------------------------------
u1 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

-----------------------------------------
u2 
 [[1 2 3 4 5]
 [5 6 7 8 9]]


## 
Insert And Delete From Arrays 

In [64]:
#Append an Array to another array

r=np.array([[1,2,3,4], [5,6,7,8]]) 
print("r","\n",r)




r 
 [[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# r= my array , 0 = The location , 

r1=np.insert(r, 0, [[11,12,13,14]], axis=0)
print("r1", "\n",r1)


r1 
 [[11 12 13 14]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [67]:
r2=np.insert(r, 4, [10,11], axis=1)
print("r2","\n",r2,"\n")


r2 
 [[ 1  2  3  4 10]
 [ 5  6  7  8 11]] 



In [68]:
print(r,"\n\n",r1,"\n\n",r2,"\n\n")



[[1 2 3 4]
 [5 6 7 8]] 

 [[11 12 13 14]
 [ 1  2  3  4]
 [ 5  6  7  8]] 

 [[ 1  2  3  4 10]
 [ 5  6  7  8 11]] 




In [69]:
r3=np.delete(r,1,axis=1) 
print("r3","\n", r3,"\n")

r3 
 [[1 3 4]
 [5 7 8]] 



##
Select Array Subset


In [ ]:

#S elect Subset of an Array
a=np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25]])
print(a)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# Try to print only 11,12,16,17
#       Rows , Columns
print(a[2:4 , 0:2])

# if you wanna understand this code "a[2:4 , 0:2]" , '2:4' ==> i wanna rows from 2 and 3 , '0:2' ==> i wanna columns from 0 to 1 



[[11 12]
 [16 17]]


In [78]:
# LOOK To UnderStand 
# Now i will Print 13,14,18,19

b = a[2:4 , 2:4]

print(b)

[[13 14]
 [18 19]]


**This NoteBook Made By : Abdelrahman Alaa**

 **LinkedIn:**
  **https://www.linkedin.com/in/abdelrahman1alaa**

**GitHub** : **https://github.com/abdelrahman1alaa**